version: '3'

services:
  seckill:
    image: jesper-seckill:latest
    container_name: seckill-container
    ports:
      - "8082:8082"
      - "9999:9999"
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx512m -Xms512m
    networks:
      - seckill-network

networks:
  seckill-network:
    external: true 